spring.datasource.url=jdbc:postgresql://dpg-cvi0ejpopnds73fopqng-a:5432/assetdb_uwyz
spring.datasource.username=assetdb_uwyz_user
spring.datasource.password=hIn7N2VM9l8ZvhXXLMjjeK3CUoTr3t5V
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
logging.level.org.springframework.security=DEBUG
